data:
  raw: "data/raw"
  processed: "data/processed"
  interim: "data/interim"
  external: "data/external"

models:
  model_path: "models"

PostGres_DB:
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PWD:  ${{ secrets.DB_PWD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: 5432